testing:
  hosts:
    # bastion.staging.coscene.site:
    #   ansible_user: ecs-user
    ansible-test:
      ansible_user: root
  vars:
    server_url: https://api.coscene.cn
    project_slug: default/yang-ming-zhuan-yong
    api_key: MTY3OTNjMTg1YmI0MTcxZTlmMzlhMmFhOGM5OTVkNzBiZDE4MzYyZWJjYTFjOTcwYmI0MzlkZjFjMmJmNjI2Mw==
    base_dir: /root/launch/error_logs